Health-Education-England/tis-revalidation-v2

.prettierrc, .stylelintrc, package-lock.json, package.json, src/styles.scss
added husky, prettier, stylelint, stylelint-prettier packages for scss formatting and linting
added lint:styles npm package
=> TISNEW-3931 | fe scss formatting

angular.json, package-lock.json, package.json, projects/hee-shared/README.md, projects/hee-shared/karma.conf.js, projects/hee-shared/ng-package.json, projects/hee-shared/package-lock.json, projects/hee-shared/package.json, projects/hee-shared/src/lib/analytics/analytics.errorhandler.ts, projects/hee-shared/src/lib/analytics/analytics.module.ts, projects/hee-shared/src/public-api.ts, projects/hee-shared/src/test.ts, projects/hee-shared/tsconfig.lib.json, projects/hee-shared/tsconfig.lib.prod.json, projects/hee-shared/tsconfig.spec.json, projects/hee-shared/tslint.json, src/app/app.module.ts, src/environments/environment.interface.ts, src/environments/environment.staging.ts, src/environments/environment.ts, tsconfig.json
Shared library implemented
Analytics module configured
Environments Interface set-up
#TISNEW-3932
=> Shared modules

projects/hee-shared/src/lib/analytics/analytics.module.ts, src/app/app.component.html, src/app/app.component.spec.ts, src/app/app.component.ts
- fix broken unit tests
- remove empty scss file
- converted non arrow function in `hee-shared/src/lib/analytics/analytics.module.ts:80:23` as wasn't able to commit
=> fix unit tests

.gitignore, projects/hee-shared/src/lib/analytics/analytics.errorhandler.ts, projects/hee-shared/src/lib/analytics/analytics.module.spec.ts, projects/hee-shared/src/lib/analytics/analytics.module.ts, projects/hee-shared/src/lib/hotjar/hotjar.module.spec.ts, projects/hee-shared/src/lib/hotjar/hotjar.module.ts, projects/hee-shared/src/lib/mock.test.component.ts, projects/hee-shared/src/lib/utilities.functions.ts, projects/hee-shared/src/public-api.ts, sonar-project.properties, src/app/app.module.ts
Configured hotjar for production and sonarcloud
#TISNEW-3933
=> 3rd party tools

projects/hee-shared/src/lib/analytics/analytics.module.spec.ts, projects/hee-shared/src/lib/hotjar/hotjar.module.spec.ts, projects/hee-shared/src/lib/hotjar/hotjar.module.ts, projects/hee-shared/src/public-api.ts, sonar-project.properties
fixed potential bugs as suggested by sonar cloud.
=> SONARCLOUD bug fixes

src/app/core/trainee/trainee.interfaces.ts, src/app/core/trainee/trainee.service.ts, src/environments/environment.interface.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
- created ITrainee interface
- created TraineeService
- updated environment files and added new endpoint details
=> TISNEW-4039 feat: mock endpoint and interface for trainees

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/dashboard/dashboard-routing.module.ts, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.module.ts, src/app/dashboard/under-notice/under-notice.component.html, src/app/dashboard/under-notice/under-notice.component.spec.ts, src/app/dashboard/under-notice/under-notice.component.ts, src/app/shared/shared.module.ts
- create `under-notice` child route and updated dashboard routing
- fetch and display mock trainee data on ui using nhs table
- created shared module
note: will add state management and tests in separate prs
=> TISNEW-4024 feat: list and display trainees

src/app/app-routing.module.ts, src/app/shared/page-not-found/page-not-found.component.html, src/app/shared/page-not-found/page-not-found.component.spec.ts, src/app/shared/page-not-found/page-not-found.component.ts, src/app/shared/shared.module.ts
Tisnew 4044 page not found route
=> Tisnew 4044 page not found route

src/app/core/trainee/trainee.interfaces.ts, src/app/dashboard/under-notice/under-notice.component.html, src/environments/environment.ts
the data model is still wip from the BE but for now this is the required data model for trainees for this sprint. note: this data model is subject to change still
=> TISNEW-4041 fix: update dashboard data model

src/app/core/trainee/trainee.interfaces.ts, src/app/dashboard/under-notice/under-notice.component.html, src/environments/environment.ts
requested to change `designated body` to `Programme membership type`
=> TISNEW-4024 chore: tweak data model

package-lock.json, package.json, src/app/app.module.ts, src/app/core/trainee/trainee.service.ts, src/app/dashboard/dashboard.module.ts, src/app/dashboard/under-notice/state/under-notice.actions.ts, src/app/dashboard/under-notice/state/under-notice.state.spec.ts, src/app/dashboard/under-notice/state/under-notice.state.ts, src/app/dashboard/under-notice/under-notice.component.spec.ts, src/app/dashboard/under-notice/under-notice.component.ts, src/app/shared/shared.module.ts, src/environments/environment.interface.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
- moved ngxs modules to shared module to de clutter app module
- added ngxs loggin plugin - enable for dev mode only
- plugged in state management for dashboard > under notice route
- some unit tests for the state
=> TISNEW-4024 feat: add state management to dashboard

package-lock.json, package.json, src/app/app.module.ts, src/app/dashboard/dashboard.component.spec.ts, src/app/dashboard/dashboard.module.ts, src/app/dashboard/under-notice/state/under-notice.state.ts, src/app/dashboard/under-notice/under-notice.component.html, src/app/dashboard/under-notice/under-notice.component.spec.ts, src/app/dashboard/under-notice/under-notice.component.ts, src/app/material/material.module.ts, src/app/shared/page-not-found/page-not-found.component.spec.ts, src/app/shared/shared.module.ts, src/environments/environment.ts, src/index.html, src/styles.scss
- added material to repo
- created material module and consumed `MatProgressSpinnerModule` to leverage a spinner
- updated shared module
- added api delay for local development to visually see spinner
=> Tisnew 4041 add loading spinner

karma.conf.js, package-lock.json, package.json
- added ci script for unit tests
- also added mocha reporter https://www.npmjs.com/package/karma-mocha-reporter for clearer output
=> feat: ci script for unit tests

src/app/shared/main-navigation/mat-main-nav/desktop-menu/desktop-menu.component.scss
=> bug: added ::ng-deep to flex-wrap desktop menu

cypress/integration/app/dashboard/under-notice/under-notice.spec.ts, src/app/core/trainee/trainee.interfaces.ts, src/app/dashboard/under-notice/under-notice.component.html, src/app/dashboard/under-notice/under-notice.component.ts, src/app/shared/material/material.module.ts, src/scss/_material.scss, src/scss/_nhsuk.scss, src/scss/nhsuk/all.scss, src/scss/nhsuk/settings/_all.scss, src/scss/nhsuk/settings/_breakpoints.scss, src/scss/nhsuk/settings/_colours.scss, src/styles.scss
- prettified scss files, removed duplicate & commented css
- replaced NHS toolkit table code with angular material table
=> Tisnew 4114 replace nhs toolkit table with angular material

src/app/dashboard/dashboard-routing.module.ts, src/app/dashboard/dashboard.module.ts, src/app/dashboard/revalidation-form/revalidation-form.component.html, src/app/dashboard/revalidation-form/revalidation-form.component.scss, src/app/dashboard/revalidation-form/revalidation-form.component.spec.ts, src/app/dashboard/revalidation-form/revalidation-form.component.ts, src/app/dashboard/revalidation-history/PeriodicElement.ts, src/app/dashboard/revalidation-history/revalidation-history.component.html, src/app/dashboard/revalidation-history/revalidation-history.component.scss, src/app/dashboard/revalidation-history/revalidation-history.component.spec.ts, src/app/dashboard/revalidation-history/revalidation-history.component.ts, src/app/dashboard/revalidation-notes/revalidation-notes.component.html, src/app/dashboard/revalidation-notes/revalidation-notes.component.scss, src/app/dashboard/revalidation-notes/revalidation-notes.component.spec.ts, src/app/dashboard/revalidation-notes/revalidation-notes.component.ts, src/app/dashboard/trainee-summary/trainee-summary.component.html, src/app/dashboard/trainee-summary/trainee-summary.component.spec.ts, src/app/dashboard/trainee-summary/trainee-summary.component.ts, src/app/dashboard/under-notice/under-notice.component.html, src/app/dashboard/under-notice/under-notice.component.spec.ts, src/app/dashboard/under-notice/under-notice.component.ts, src/app/shared/material/material.module.ts, src/main.ts, src/scss/_material.scss, src/scss/utilities/_utilities.scss
=> Tisnew 4109

cypress/integration/app/trainees/trainees.spec.ts, src/app/core/trainee/trainee.interfaces.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/app/trainees/trainee-list/trainee-list.component.html, src/app/trainees/trainee-list/trainee-list.component.ts, src/environments/environment.ts
TISNEW-4178
- FE code updates due to BE changes
- restricted sorting on specified columns
- fixed/updated tests due to above
=> refactor: tweaks to model and FE code due to BE api changes

src/app/core/trainee/constants.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/trainee-list/trainee-list.component.spec.ts
TISNEW-4179
- unit tests to cover sorting functionality for trainee list and reset trainee list
- also corrected default sorting direction from asc to desc
=> test: unit tests for trainee list

cypress/integration/app/trainees/trainees.spec.ts
TISNEW-4179
- more trainee list e2e tests to cover sorting and clear sorting scenarios
=> test: trainee list e2e tests

src/app/app.component.spec.ts, src/app/app.component.ts, src/app/core/trainee/trainee.interfaces.ts, src/app/dashboard/revalidation-form/revalidation-form.component.spec.ts, src/app/dashboard/trainee-summary/trainee-summary.component.spec.ts, src/app/shared/material/material.module.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts, src/app/trainees/state/trainees.actions.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.html, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.spec.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts, src/app/trainees/trainee-list/trainee-list.component.spec.ts, src/app/trainees/trainee-list/trainee-list.component.ts, src/app/trainees/trainees.component.html, src/app/trainees/trainees.component.spec.ts, src/app/trainees/trainees.module.ts, src/environments/environment.ts
TISNEW-4186
- pagination feature for trainees list
- updated `IGetTraineesResponse` interface as per BE changes
- updated `getTrainees` FE mock endpoint
- fixed all outstanding warnings in unit testing around trainee details screen components
- removed redundant 2 tests from `AppComponent`
=> feat: trainees list paginator

cypress/integration/app/trainees/reset-trainee-list/reset-trainee-list.spec.ts, cypress/integration/app/trainees/trainee-list-paginator/trainee-list-paginator.spec.ts, cypress/integration/app/trainees/trainee-list/trainee-list.spec.ts, src/app/trainees/state/trainees.state.ts, src/environments/environment.ts
TISNEW-4185
- e2e tests for trainees-list pagination
- split e2e tests in to smaller files 
- updated mocky with more mock trainees (contains 21)
- updated parameter name for page as per latest BE changes
=> feat: pagination e2e tests

src/app/trainees/trainees-routing.module.ts, src/app/trainees/trainees.component.html
simplify trainees list route as at this moment in time nested routes are not needed for trainees-list
=> chore: simplify trainees list route

proxy.conf.json, src/app/app.module.ts, src/app/core/trainee/trainee.service.ts, src/app/shared/main-navigation/mat-main-nav/desktop-menu/desktop-menu.component.html, src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.scss, src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts, src/environments/environment.interface.ts, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts, src/scss/utilities/_utilities.scss
localhost replace dev local home IP
scss reduced into utilities
environment variables refactored for GA, hotjar and removed redundant host
desktop menu linked to dev reval app and css z-index fix
=> fix: local dev environment fixes

projects/hee-shared/src/lib/analytics/analytics.errorhandler.ts, projects/hee-shared/src/lib/analytics/analytics.module.ts
gtag was initially used but reverting to older ga due to uniform use across HEE
=> fix: analytics beacon

src/app/core/trainee/trainee.service.spec.ts, src/app/core/trainee/trainee.service.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.html, src/app/trainees/state/trainees.actions.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/app/trainees/trainee-filters/trainee-filters.component.html, src/app/trainees/trainee-filters/trainee-filters.component.scss, src/app/trainees/trainee-filters/trainee-filters.component.spec.ts, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.spec.ts, src/app/trainees/trainee-list/trainee-list.component.spec.ts, src/app/trainees/trainee-list/trainee-list.component.ts, src/app/trainees/trainee-search/trainee-search.component.html, src/app/trainees/trainees.component.html, src/app/trainees/trainees.component.scss, src/app/trainees/trainees.component.ts, src/app/trainees/trainees.module.ts, src/environments/environment.ts
TISNEW-4154 - implemented trainees list filtering
- added new `AllDoctorsFilter` and `UnderNoticeFilter` actions, selectors and related events
- added new `TraineeFiltersComponent` alongside some minor ui/scss tweaks
- extracted generation of http params in to service so code can be re used and easier unit testing
- tweaked and added more unit tests
=> feat: trainees list filter

cypress/integration/app/trainees/trainee-filters/trainee-filters.spec.ts, cypress/integration/app/trainees/trainee-search/trainee-search.spec.ts
TISNEW-4205 e2e browser automation tests for trainees search
=> test: trainees search e2e tests

src/app/trainees/trainee-filters/trainee-filters.component.scss, src/app/trainees/trainee-search/trainee-search.component.html, src/app/trainees/trainee-search/trainee-search.component.scss, src/app/trainees/trainee-search/trainee-search.component.ts
leverage css grid to fix mobile view for search form
=> bug: search icon mobile view fix

.github/workflows/deploy.yml, package.json
- add unit tests to github workflow
- rename & optimize build script
=> chore: add unit tests to github workflow, rename & optimize script

src/app/core/trainee/trainee.service.spec.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts, src/app/trainees/state/trainees.actions.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/app/trainees/trainee-filters/trainee-filters.component.spec.ts, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.spec.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts, src/app/trainees/trainee-list/trainee-list.component.spec.ts, src/app/trainees/trainee-list/trainee-list.component.ts, src/app/trainees/trainee-search/trainee-search.component.spec.ts, src/app/trainees/trainee-search/trainee-search.component.ts
tidy up and remove `Trainees` keyword from action class names for consistency
=> refactor: tidy trainees actions

src/app/trainees/trainee-search/trainee-search.component.html
TISNEW-4524
relocate search icon so its visually better placed. also replace placeholder with <mat-label> for better accessibility
=> refactor: relocate search icon

src/app/trainees/reset-trainee-list/reset-trainee-list.component.html, src/app/trainees/trainee-filters/trainee-filters.component.html, src/app/trainees/trainee-filters/trainee-filters.component.scss, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainee-search/trainee-search.component.html, src/app/trainees/trainee-search/trainee-search.component.scss, src/app/trainees/trainees.component.html, src/app/trainees/trainees.component.scss
TISNEW-4524
uniform ui by utilising tab groups, menu action dropdown
=> refactor: utilise tab groups

src/app/app-routing.module.ts, src/app/concerns/concern-list/concern-list.component.html, src/app/concerns/concern-list/concern-list.component.spec.ts, src/app/concerns/concern-list/concern-list.component.ts, src/app/concerns/concerns-routing.module.ts, src/app/concerns/concerns.component.html, src/app/concerns/concerns.component.spec.ts, src/app/concerns/concerns.component.ts, src/app/concerns/concerns.module.ts, src/app/concerns/state/concerns.actions.ts, src/app/concerns/state/concerns.state.spec.ts, src/app/concerns/state/concerns.state.ts, src/app/trainee/trainee.component.spec.ts, src/app/trainee/trainee.component.ts, src/app/trainees/trainee-search/trainee-search.component.spec.ts
TISNEW-4572
create concerns list components, route and module
=> feat: create concerns list components, route and module

src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.html, src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.scss, src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.ts, src/app/trainees/trainees.component.html, src/scss/_material.scss
removed sticky navigation
revised desktop navigation from 2 rows to one row
fixed bug with skip to maincontent link
TISNEW-4577
=> feat: UI optimisation

src/app/concerns/concerns.interfaces.ts, src/app/concerns/state/concerns.state.ts, src/app/shared/records/state/records.actions.ts, src/app/shared/records/state/records.state.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts, src/app/trainees/state/trainees.actions.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts, src/app/trainees/trainee-list/trainee-list.component.ts, src/app/trainees/trainee-search/trainee-search.component.ts
TISNEW-4523
refactor to create a shared state so it can be extended and consumed by both trainees list and concerns list
=> refactor: create shared state

package-lock.json, package.json
security vulnerabilities and dependency resolutions
run npm install after pull to confirm 0 vulnerabilities in report
=> fix: npm audits

src/app/concerns/concern-list/concern-list.component.spec.ts, src/app/concerns/concerns.interfaces.ts, src/app/concerns/services/concerns.service.spec.ts, src/app/concerns/services/concerns.service.ts, src/app/concerns/state/concerns.state.spec.ts, src/app/concerns/state/concerns.state.ts, src/app/shared/records/services/records.service.spec.ts, src/app/shared/records/services/records.service.ts, src/app/shared/records/state/records.state.ts, src/app/trainees/services/trainees.service.spec.ts, src/app/trainees/services/trainees.service.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/environments/environment.interface.ts, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-4520
create concerns list interface, mock api & common code abstraction
=> refactor: create concerns list interface, mock api & common code abstraction

Dockerfile, nginx/nginx.conf
uncommented latest cache-control lines to see if index redirect works
=> fix: nginx config fix

Dockerfile, nginx/nginx.conf
added cache-control map settings to see if site rendering can be sped-up
=> Nginx config fix

ngsw-config.json, src/app/trainee/mock-data/trainee-spec-data.ts, src/app/trainee/revalidation-history.interface.ts, src/app/trainee/revalidation-history/revalidation-history.component.html, src/app/trainee/revalidation-history/revalidation-history.component.ts, src/app/trainee/revalidation-table/revalidation-table.component.html, src/app/trainee/revalidation-table/revalidation-table.component.scss, src/app/trainee/revalidation-table/revalidation-table.component.ts, src/app/trainee/services/revalidation-history.service.ts, src/app/trainee/state/revalidation-history.state.spec.ts, src/app/trainee/state/revalidation-history.state.ts, src/app/trainee/trainee-details/trainee-details.component.html, src/app/trainee/trainee.resolver.spec.ts, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts
modified PWA config
configured interface and data related elements to match backend
amended tests to reflect changes
TISNEW-4328
=> feat: data-bind to backend

src/app/shared/records/record-list/record-list.component.spec.ts, src/app/trainees/services/trainees.service.spec.ts, src/app/trainees/state/trainees.state.ts, src/app/trainees/trainees.interfaces.ts
consume RevalidationStatus enum
=> refactor: consume RevalidationStatus enum

nginx/nginx.conf
re-added headers requested by dev-ops and put location tags inside server directive
=> Fix nginx config2

src/app/concerns/concern-list/concern-list.component.ts, src/app/trainees/trainee-list/trainee-list.component.ts
disable view encapsulation so that css doesn't clash between concerns and trainees list
=> fix: disable view encapsulation

src/app/trainees/state/trainees.state.spec.ts
=> test: fix trainees spec warnings

package-lock.json, src/app/concerns/concern-list/concern-list.component.spec.ts, src/app/concerns/concern-list/concern-list.component.ts, src/app/concerns/constants.ts, src/app/shared/records/record-list/record-list.component.spec.ts, src/app/shared/records/record-list/record-list.component.ts
- increase code coverage list components
- relocated column data to a constant so it can be reused
=> test: increase code coverage list components

.github/workflows/deploy.yml, nginx/nginx.conf, package-lock.json, src/app/trainee/revalidation-history.interface.ts, src/app/trainee/revalidation-history/revalidation-history.component.html, src/app/trainee/revalidation-history/revalidation-history.component.ts, src/app/trainee/revalidation-table/revalidation-table.component.html
added nginx gzip optimization config
=> fix: revalidation history bindings

src/app/app-routing.module.ts, src/app/connections/connection-list/connection-list.component.html, src/app/connections/connection-list/connection-list.component.spec.ts, src/app/connections/connection-list/connection-list.component.ts, src/app/connections/connections-routing.module.ts, src/app/connections/connections.component.html, src/app/connections/connections.component.spec.ts, src/app/connections/connections.component.ts, src/app/connections/connections.interfaces.ts, src/app/connections/connections.module.ts, src/app/connections/constants.ts, src/app/shared/records/services/records.service.ts, src/app/trainee/trainee.component.ts
TISNEW-4623
create route, module, interface and components for connections
=> feat: create route, module, interface and components for connections

src/environments/environment.interface.ts, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-4621
create mock FE endpoint `http://www.mocky.io/v2/5ecfc8283200006500e3d5ae` and update environment files
=> feat: mock connections api

src/app/concerns/concern-list/concern-list.component.ts, src/app/shared/records/record-list/record-list.component.spec.ts, src/app/shared/records/services/records.service.ts, src/app/trainees/constants.ts, src/app/trainees/trainee-list/trainee-list.component.ts
TISNEW-4620
simplify records service methods by passing in relevant action to baseclass so that future new list pages can be easily created.
- also relocated trainees list column data so that it can be reused
- fixed unit tests
=> refactor: simplify records service

src/app/concerns/concerns.interfaces.ts, src/app/trainees/trainee-filters/trainee-filters.component.html, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainees.interfaces.ts
TISNEW-4620
tidy up enums and trainee filters
=> refactor: tidy up enums and trainee filters

src/app/concerns/concern-list/concern-list.component.spec.ts, src/app/concerns/concern-list/concern-list.component.ts, src/app/concerns/concerns.interfaces.ts, src/app/concerns/constants.ts, src/app/connections/connection-list/connection-list.component.html, src/app/connections/connection-list/connection-list.component.spec.ts, src/app/connections/connection-list/connection-list.component.ts, src/app/connections/connections.interfaces.ts, src/app/connections/connections.module.ts, src/app/connections/constants.ts, src/app/connections/services/connections.service.spec.ts, src/app/connections/services/connections.service.ts, src/app/connections/state/connections.actions.ts, src/app/connections/state/connections.state.spec.ts, src/app/connections/state/connections.state.ts, src/app/shared/records/constants.ts, src/app/shared/records/record-list/record-list.component.spec.ts, src/app/trainees/constants.ts, src/app/trainees/trainee-filters/trainee-filters.component.html, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainee-list/trainee-list.component.ts, src/app/trainees/trainees.interfaces.ts, src/environments/environment.ts
TISNEW-4620
connections list screen
=> feat: connections list screen

src/app/shared/records/record-list/record-list.component.spec.ts, src/app/shared/records/record-list/record-list.component.ts, src/app/shared/records/services/records.service.spec.ts, src/app/shared/records/services/records.service.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts, src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts, src/app/trainees/trainee-filters/trainee-filters.component.spec.ts, src/app/trainees/trainee-filters/trainee-filters.component.ts, src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts, src/app/trainees/trainee-search/trainee-search.component.ts
tackle a TODO by simplifying route update
=> refactor: simplify update route

projects/hee-shared/ng-package.json, projects/hee-shared/package.json, src/app/app.module.ts, src/app/core/auth/auth.initializer.ts, src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.html, src/app/shared/material/material.module.ts, src/app/trainee/revalidation-history/revalidation-history.component.html, src/app/trainee/revalidation-history/revalidation-history.component.scss, src/app/trainee/revalidation-history/revalidation-history.component.ts, src/app/trainee/revalidation-table/revalidation-table.component.html, src/scss/_material.scss, src/scss/_nhsuk.scss, src/scss/utilities/_utilities.scss
UI enhancements and agreement legal notice prepared for data-binding
=> Ui history form and route

.github/workflows/deploy.yml
=> feat: CICD pipeline run linting, build and tests on pull requests

src/app/shared/records/services/records.service.spec.ts, src/app/shared/records/services/records.service.ts
increase records service coverage
=> test: increase records service coverage

.github/workflows/deploy.yml
Fix the dockerize step not having build artifacts available to build the
image with.
Add backup of artifacts to S3 bucket.
NO-TICKET
=> chore: Fix workflow and add artifact backups

src/app/trainees/trainee-filters/trainee-filters.component.html, src/app/trainees/trainees.interfaces.ts
=> fix: correct query param

src/app/shared/records/record-list/record-list.component.html, src/environments/environment.ts, src/scss/utilities/_utilities.scss
TISNEW-4634
highlight under notice trainees with a subtle red transparent bg color and a left border in nhs red
=> feat: visual que for undernotice trainees

src/app/shared/records/record-list/record-list.component.html, src/environments/environment.ts
TISNEW-4634
correct property value binding
=> fix: property value binding

src/app/trainee/revalidation-history/revalidation-history.component.html, src/app/trainee/revalidation-history/revalidation-history.component.scss
TISNEW-4210
fix for desktop layout issue. it will be a bit hard to tell what has changed in the markup due to prettier auto formatting but here are the markup changes;
from
`<div class="revalidation-history" [ngClass]="{ 'd-flex': !device.isHandset }">`
to
`<div class="revalidation-history" [ngClass]="{ 'd-grid': !device.isHandset }">`
from
`<div class="w-100 bg-white">`
to
`<div class="main-col d-grid bg-white">`
=> fix: desktop layout issue

src/app/shared/records/record-list/record-list.component.html
NO-TICKET
remove `role=button` from `tr` to improve assessibility
=> refactor: assessibility improvement

.github/workflows/deploy.yml
NO-TICKET
optimize pipeline by removing angular cli install step from pipeline as its not needed
=> refactor: optimize pipeline

proxy.conf.json, src/app/concerns/concern-list/concern-list.component.ts, src/app/concerns/concerns.interfaces.ts, src/app/concerns/constants.ts, src/app/concerns/state/concerns.state.ts, src/app/trainee/revalidation-history/revalidation-history.component.spec.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-4597
consume concerns endpoint and make relevant changes. also update mocky and proxy
NOTE: mocky has updated its url from `https://www.mocky.io/v2/{{hashHere}}` to `https://run.mocky.io/v3/{{hashHere}}` so i have updated the mock endpoints too
=> feat: consume concerns endpoint

.github/workflows/deploy.yml
fix build command for staging environment
=> fix: build command for staging environment

src/app/concerns/constants.ts, src/app/concerns/state/concerns.state.ts, src/app/connections/constants.ts, src/app/connections/state/connections.state.ts, src/app/shared/records/constants.ts, src/app/shared/records/record-list/record-list.component.spec.ts, src/app/trainees/constants.ts, src/app/trainees/state/trainees.state.spec.ts, src/app/trainees/state/trainees.state.ts, src/environments/environment.local.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-4597
fe tweaks to consume concerns api
=> refactor: fe tweaks to consume concerns api

src/app/shared/records/record-list/record-list.component.html, src/app/trainee/revalidation-table/revalidation-table.component.html, src/scss/material/_index.scss, src/scss/utilities/_utilities.scss
=> refactor: sass mixin refactor

src/app/app-routing.module.ts, src/app/concern/concern-routing.module.ts, src/app/concern/concern.component.html, src/app/concern/concern.component.spec.ts, src/app/concern/concern.component.ts, src/app/concern/concern.module.ts, src/app/recommendation/recommendation-history/recommendation-history.component.scss, src/app/recommendation/recommendation.resolver.ts, src/app/shared/details/nav-bar/nav-bar.component.ts, src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts
TISNEW-4737
create skeleton concern details page + tidy up for nav bar component anchor urls
=> feat: concern details screen

src/app/concern/concern-routing.module.ts, src/app/concern/concern.module.ts, src/app/recommendation/recommendation-history/recommendation-history.component.scss, src/app/recommendation/recommendation-routing.module.ts, src/app/recommendation/recommendation.resolver.ts, src/app/shared/details/details-side-nav/details-side-nav.component.spec.ts, src/app/shared/details/details-side-nav/details-side-nav.component.ts, src/app/shared/details/record-details/record-details.component.html, src/app/shared/details/record-details/record-details.component.scss, src/app/shared/details/record-details/record-details.component.spec.ts, src/app/shared/details/record-details/record-details.component.ts
TISNEW-4737 
wrapper component for details screen which is now being used on concern details and recommendation details screens
=> refactor: wrapper component for details screen

src/app/recommendation/confirm-recommendation/confirm-recommendation.component.html, src/app/recommendation/confirm-recommendation/confirm-recommendation.component.spec.ts, src/app/recommendation/confirm-recommendation/confirm-recommendation.component.ts, src/app/recommendation/recommendation-history/recommendation-history.component.ts, src/app/recommendation/recommendation-table/recommendation-table.component.ts, src/app/recommendation/state/recommendation-history.state.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-4737
relocate code from history component to confirm recommendation route/component
=> refactor: confirm recommendation route

src/app/recommendation/confirm-recommendation/confirm-recommendation.component.html, src/app/recommendation/mock-data/recommendation-spec-data.ts, src/app/shared/details/details-side-nav/details-side-nav.component.html, src/app/shared/details/details-side-nav/details-side-nav.component.ts, src/app/shared/details/details-side-nav/details-side-nav.interfaces.ts, src/app/shared/details/details-side-nav/service/details-side-nav.service.ts, src/app/shared/details/details-side-nav/state/details-side-nav.state.spec.ts, src/app/shared/details/details-side-nav/state/details-side-nav.state.ts, src/environments/environment.mocky.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-4737
split endpoints FE work to align with BE changes
=> refactor: split endpoints

src/app/recommendation/confirm-recommendation/confirm-recommendation.component.ts, src/app/recommendation/create-recommendation/create-recommendation.component.html, src/app/recommendation/create-recommendation/create-recommendation.component.ts
=> fix: uniform form reset and redirect to parent route

src/environments/constants.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
NO TICKET
extract common environment config
=> refactor: extract common environment config

package-lock.json, src/app/app-routing.module.ts
decouple all lazy modules loading at once as affects initial age-load
=> chore: decouple all lazy modules 

src/environments/constants.ts, src/environments/environment.mocky.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
NO-TICKET
extract common aws config
=> refactor: extract common aws config

src/app/core/auth/auth.service.ts, src/app/recommendation/create-recommendation/create-recommendation.component.spec.ts, src/app/recommendation/create-recommendation/create-recommendation.component.ts, src/app/shared/main-navigation/mat-main-nav/status-bar/status-bar.component.html, src/app/shared/main-navigation/mat-main-nav/status-bar/status-bar.component.spec.ts, src/app/shared/main-navigation/mat-main-nav/status-bar/status-bar.component.ts
=> feat: get authenticated user details from cognito

src/app/shared/admins/state/admins.state.ts
=> bug: fix missing param

src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts
=> fix: added missing concerns link to header

src/app/concerns/concerns.interfaces.ts, src/app/concerns/state/concerns.actions.ts, src/app/concerns/state/concerns.state.ts
NO-TICKET
reuse enum on concerns
=> refactor: reuse enum on concerns

src/app/shared/admins/admins.interfaces.ts, src/app/shared/admins/services/admins.service.spec.ts, src/app/shared/admins/services/admins.service.ts, src/app/shared/admins/state/admins.actions.ts, src/app/shared/admins/state/admins.state.spec.ts, src/app/shared/admins/state/admins.state.ts, src/app/shared/records/allocate-admin-actions/allocate-admin-actions.component.ts, src/app/shared/records/allocate-admin-autocomplete/allocate-admin-autocomplete.component.html, src/app/shared/records/allocate-admin-autocomplete/allocate-admin-autocomplete.component.spec.ts, src/app/shared/records/allocate-admin-autocomplete/allocate-admin-autocomplete.component.ts, src/app/shared/records/record-list/record-list.component.html, src/environments/constants.ts, src/environments/environment.interface.ts, src/environments/environment.mocky.ts
TISNEW-4831
feat: allocate admin wire up endpoint
- added new add, remove submit, success, error admin actions
- added new state methods that listen to above listed actions
- created new interface and added, consumed allocateAdmin api 
- updated unit tests
=> feat: allocate admin wire up endpoint

src/app/concern/concern.component.html, src/app/concern/create-concern/create-concern.component.html, src/app/concern/create-concern/create-concern.component.scss, src/app/concern/create-concern/create-concern.component.spec.ts, src/app/concern/create-concern/create-concern.component.ts
Dummy handlers for upload and drag-drop
=> Details view link fix

src/app/app.component.ts, src/app/shared/admins/state/admins.state.spec.ts
=> fix: aws group name

package-lock.json, src/app/shared/page-not-found/page-not-found.component.html
NO-TICKET
- removed nhs uk styles as reval is using material 
- added some spacing around the main content
=> fix: tweak layout on page not found

package.json, src/app/app.module.ts, src/app/factories/error-handler.factory.ts, src/environments/environment.interface.ts, src/environments/environment.mocky.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
=> chore: add Sentry

package-lock.json, src/app/concern/comments/comments.component.ts, src/app/concern/concern.interfaces.ts, src/app/concern/file-uploader/file-uploader.component.html, src/app/concern/file-uploader/file-uploader.component.spec.ts, src/app/concern/file-uploader/file-uploader.component.ts, src/app/concern/services/upload/upload.service.ts, src/app/concern/state/concern.actions.ts, src/app/concern/state/concern.state.spec.ts, src/app/concern/state/concern.state.ts, src/app/recommendation/confirm-recommendation/confirm-recommendation.component.ts, src/app/recommendation/create-recommendation/create-recommendation.component.ts, src/app/shared/admins/services/admins.service.ts, src/app/shared/admins/state/admins.state.spec.ts, src/app/shared/admins/state/admins.state.ts, src/app/shared/services/snack-bar/snack-bar.service.spec.ts, src/app/shared/services/snack-bar/snack-bar.service.ts, src/environments/constants.ts, src/environments/environment.interface.ts, src/environments/environment.mocky.ts
TISNEW-4914
feat: consume upload api
- also extracted common code for opening up a snackbar (material's version of a toaster notification)
- updated unit tests
=> feat: consume upload api

src/app/concern/file-uploader/file-uploader.component.html, src/app/concern/file-uploader/file-uploader.component.ts, src/app/concern/services/upload/upload.service.ts, src/app/concern/state/concern.actions.ts, src/app/concern/state/concern.state.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.html, src/app/concern/uploaded-files-list/uploaded-files-list.component.spec.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.ts
TISNEW-5021
feat: consume file list api
- also added loading spinners whilst file is uploading and whilst uploaded files are being retrieved
=> feat: consume file list api

src/app/concern/constants.ts, src/app/concern/file-uploader/file-uploader.component.ts, src/app/concern/state/concern.state.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.html, src/app/concern/uploaded-files-list/uploaded-files-list.component.scss, src/app/concern/uploaded-files-list/uploaded-files-list.component.ts, src/scss/utilities/_utilities.scss
TISNEW-5021
feat: layout tweaks to list files
- consume list endpoint response tweaks on the FE
- leverage css grid to handle desktop/mobile views
- handle icon display
=> feat: layout tweaks to list files

src/app/concern/constants.ts, src/app/concern/services/upload/upload.service.spec.ts, src/app/concern/services/upload/upload.service.ts, src/app/concern/state/concern.actions.ts, src/app/concern/state/concern.state.spec.ts, src/app/concern/state/concern.state.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.html, src/app/concern/uploaded-files-list/uploaded-files-list.component.spec.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.ts, src/environments/constants.ts, src/environments/environment.interface.ts, src/environments/environment.mocky.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts, src/environments/environment.ts
TISNEW-5023
feat: consume delete api
- also created environment variable for `bucketName`
- unit tests
=> feat: consume delete api

src/app/concern/constants.ts, src/app/concern/file-uploader/file-uploader.component.html, src/app/concern/file-uploader/file-uploader.component.ts, src/app/concern/services/upload/upload.service.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.html, src/app/concern/uploaded-files-list/uploaded-files-list.component.ts
TISNEW-4914
feat: multiple file upload
=> feat: multiple file upload

package-lock.json, src/app/concern/constants.ts
NO-TICKET
fix: missing image icon
=> fix: missing image icon

src/app/concern/file-uploader/file-uploader.component.html
=> fix: spacing issues

src/app/factories/error-handler.factory.ts
=> chore: update Sentry DSN key

src/app/app.module.ts, src/app/concern/state/concern.actions.ts, src/app/concern/state/concern.state.ts, src/app/concerns/state/concerns.actions.ts, src/app/concerns/state/concerns.state.ts, src/app/connections/state/connections.actions.ts, src/app/connections/state/connections.state.ts, src/app/core/auth/auth.interceptor.spec.ts, src/app/core/auth/auth.interceptor.ts, src/app/recommendations/state/recommendations.actions.ts, src/app/recommendations/state/recommendations.state.spec.ts, src/app/recommendations/state/recommendations.state.ts, src/app/shared/admins/state/admins.actions.ts, src/app/shared/admins/state/admins.state.ts, src/app/shared/records/state/records.actions.ts, src/app/shared/records/state/records.state.ts, src/app/shared/services/http-error/http-error.service.spec.ts, src/app/shared/services/http-error/http-error.service.ts, src/environments/environment.mocky.ts
NO-TICKET
feat: handle http error/s in 1 place on the ui by showing material snackbar (mini toaster notification)
=> feat: http error handling

src/app/shared/records/record-list/record-list.component.html
NO-TICKET
fix: show admin component or admin name
=> fix: show admin component or admin name

src/app/concerns/concerns.component.html, src/app/concerns/concerns.component.ts, src/app/connections/connections.component.html, src/app/connections/connections.component.ts, src/app/recommendations/recommendations.component.html, src/app/recommendations/recommendations.component.ts, src/app/shared/records/record-search/record-search.component.html, src/app/shared/records/records.component.scss, src/app/shared/records/records.module.ts, src/app/shared/records/refresh-data-btn/refresh-data-btn.component.html, src/app/shared/records/refresh-data-btn/refresh-data-btn.component.spec.ts, src/app/shared/records/refresh-data-btn/refresh-data-btn.component.ts
TISNEW-5094
feat: refresh data btn
- implemented new btn component on all summary screens so a user has the option to manually refresh the data table
=> feat: refresh data btn

src/app/concern/uploaded-files-list/uploaded-files-list.component.scss, src/app/concerns/concerns.component.html, src/app/connections/connections.component.html, src/app/recommendations/recommendations.component.html, src/app/shared/records/records.component.scss, src/app/shared/records/refresh-data-btn/refresh-data-btn.component.html, src/scss/utilities/_mixins.scss
TISNEW-5094
refactor: tweak refresh btn based upon feedback
=> refactor: tweak refresh btn

src/app/recommendation/recommendation.resolver.ts, src/app/shared/services/error/error.service.spec.ts
NO-TICKET
fix: remove get recommendations call as the api isn't developed yet so staging environment just throws an error
=> fix: remove get recommendations call

package-lock.json, src/app/concerns/concerns.component.html, src/app/connections/connections.component.html, src/app/recommendations/recommendations.component.html, src/app/shared/records/refresh-data-btn/refresh-data-btn.component.html, src/app/shared/records/refresh-data-btn/refresh-data-btn.component.ts
NO-TICKET
feat: disable reset button if in allocate admin mode
=> feat: disable reset button if in allocate admin mode

src/app/shared/records/allocate-admin-btn/allocate-admin-btn.component.html, src/app/shared/records/allocate-admin-btn/allocate-admin-btn.component.spec.ts, src/app/shared/records/allocate-admin-btn/allocate-admin-btn.component.ts
NO-TICKET
feat: enhance allocate admin btn so it can act as a on/off toggle
=> feat: enhance allocate admin btn

src/app/concern/file-uploader/file-uploader.component.spec.ts, src/app/concern/file-uploader/file-uploader.component.ts
NO-TICKET
fix: ensure file selector checks file type
=> fix: ensure file selector checks file type

src/app/concern/uploaded-files-list/uploaded-files-list.component.html, src/app/concern/uploaded-files-list/uploaded-files-list.component.scss, src/scss/utilities/_layout.scss
NO-TICKET
refactor: reuse grid column
=> refactor: reuse grid column

angular.json, src/app/core/auth/auth.service.ts
import CognitoHostedUIIdentityProvider from types lib for smoother dependabot upgrade
=> fix: import CognitoHostedUIIdentityProvider from types lib

src/app/shared/admins/state/admins.state.ts
TISNEW-4981
fix: inner observable race condition
=> fix: inner observable race condition

package-lock.json, tsconfig.base.json
=> fix: CognitoHostedUIIdentityProvider is undefined

src/app/connections/connection-list/connection-list.component.ts, src/app/connections/connections.interfaces.ts, src/app/connections/constants.ts, src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts, src/environments/constants.ts, src/environments/environment.mocky.ts
TISNEW-4667
feat | consume connections api
=> feat | consume connections api

src/app/connections/connections.interfaces.ts, src/app/connections/state/connections.state.ts
TISNEW-4667
refactor: align interface to BE
=> refactor: align interface to BE

src/app/records/record-list/record-list.component.html, src/app/records/record-list/record-list.component.scss
TISNEW-5107
fix: remove highlight as per feedback
=> fix: remove highlight

src/app/concern/file-uploader/file-uploader.component.html, src/app/concern/file-uploader/file-uploader.component.scss, src/app/concern/file-uploader/file-uploader.component.spec.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.html, src/app/shared/file-bytes.pipe.spec.ts, src/app/shared/file-bytes.pipe.ts, src/app/shared/shared.module.ts
=> feat: upload documents

src/app/concern/state/concern.state.ts
=> fix: broken download fixes

src/app/concerns/concerns.resolver.ts, src/app/connections/connections.resolver.ts, src/app/recommendations/recommendations-filters/recommendations-filters.component.spec.ts, src/app/recommendations/recommendations.resolver.ts, src/app/records/record-list-paginator/record-list-paginator.component.spec.ts, src/app/records/record-list/record-list.component.spec.ts, src/app/records/record-search/record-search.component.spec.ts, src/app/records/reset-record-list/reset-record-list.component.spec.ts, src/app/records/services/records.service.ts
NO-TICKET
refactor: simplify set actions
=> refactor: simplify set actions

src/app/admins/allocate-admin-autocomplete/allocate-admin-autocomplete.component.ts
NO-TICKET
fix: admin items subscription by adding a rxjs filter
=> fix: admin items subscription

src/app/records/record-list/record-list.component.scss
NO-TICKET
refactor: fix column widths
=> refactor: fix column widths

src/app/app.component.html, src/app/records/record-list/record-list.component.html, src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.html, src/scss/utilities/_layout.scss, src/scss/utilities/_utilities.scss
loading-spinner centred
NO-TICKET
=> refactor: UI for extra-large screen max-width

src/app/records/services/records.service.ts
NO-TICKET
refactor: commonise code
=> refactor: commonise code

src/app/records/services/records.service.ts
=> fix: action name

src/app/concern/file-uploader/file-uploader.component.ts
=> fix: upload bug fix

src/app/concern/concern.interfaces.ts, src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.html, src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.ts, src/app/concern/state/concern.state.ts, src/app/concern/uploaded-files-list/uploaded-files-list.component.ts
TISNEW-4450
feat: consume api updates
- remove and swap hardcoded dropdown values with list/s from BE api response
- update state
=> feat: consume api updates

src/app/connections/connections.component.html
TISNEW-5263
feat: add search and pagination to connections
=> feat: add search and pagination to connections

src/app/concerns/constants.ts, src/app/connections/constants.ts, src/app/recommendations/constants.ts
NO-TICKET
fix: sortable columns on connections screen
=> fix: sortable columns

src/app/concerns/concerns.resolver.ts, src/app/connections/connections.interfaces.ts, src/app/connections/connections.resolver.ts, src/app/recommendations/recommendations.resolver.ts
NO-TICKET
refactor: add filters to resolvers
=> refactor: add filters to resolvers

src/environments/constants.ts
=> chore: auth details

projects/hee-shared/src/lib/analytics/analytics.errorhandler.spec.ts, projects/hee-shared/src/lib/analytics/analytics.errorhandler.ts, projects/hee-shared/src/lib/analytics/analytics.module.spec.ts, projects/hee-shared/src/lib/analytics/analytics.module.ts, projects/hee-shared/src/lib/hotjar/hotjar.module.spec.ts, projects/hee-shared/src/lib/hotjar/hotjar.module.ts, projects/hee-shared/src/lib/utilities.functions.spec.ts, projects/hee-shared/src/test.ts
=> improve hotjar and analytics coverage

src/environments/constants.ts
NO-TICKET
chore: update aws pool
=> chore: update aws pool

package-lock.json, src/app/app.module.ts, src/app/concern/create-concern-forms/concern-detail/concern-detail.component.html, src/app/concern/create-concern-forms/concern-detail/concern-detail.component.ts, src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.html, src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.ts, src/app/concern/create-concern-forms/upload-documents/upload-documents.component.html, src/app/concern/create-concern-forms/upload-documents/upload-documents.component.ts, src/app/concern/file-uploader/file-uploader.component.ts, src/app/concern/services/concern/concern.service.ts, src/app/shared/validators.ts
=> feat: add concern UI enhancements

src/app/admins/admins.module.ts, src/app/admins/admins.pipe.spec.ts, src/app/admins/admins.pipe.ts, src/app/records/record-list/record-list.component.html
=> feat: display admins full-name

src/app/details/record-details/record-details.component.scss, src/app/recommendation/create-recommendation/create-recommendation.component.html, src/app/recommendation/create-recommendation/create-recommendation.component.scss, src/app/recommendation/create-recommendation/create-recommendation.component.ts
fix: css layout for mobile
TISNEW-5304
=> feat: update text on feature recommendation button

src/environments/constants.ts
As the new pool got created so the the credentials needed to be changed accordingly
=> chore: added cognito pool credentials

src/app/records/constants.ts
=> fix: update default sort

src/app/admins/admins.interfaces.ts, src/app/admins/admins.pipe.spec.ts, src/app/admins/admins.pipe.ts, src/app/admins/services/admins.service.spec.ts, src/app/admins/state/admins.state.spec.ts, src/app/concern/concern.component.html, src/app/recommendation/recommendation-table/recommendation-table.component.html, src/app/records/record-list/record-list.component.html
=> fix: render admin full-name and email mailTo links

src/environments/environment.prod.ts, src/environments/environment.staging.ts
=> TISNEW-5393 feat: Updated hotjar id for staging and prod

angular.json, package-lock.json
=> fix: commonjs dependencies warning

package-lock.json, src/app/concerns/services/concerns.service.ts, src/app/core/auth/auth.interceptor.spec.ts, src/app/core/auth/auth.interceptor.ts, src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts, src/app/recommendations/recommendations.interfaces.ts, src/app/recommendations/recommendations.resolver.ts, src/app/recommendations/services/recommendations.service.spec.ts, src/app/recommendations/services/recommendations.service.ts, src/app/records/record-list/record-list.component.spec.ts, src/app/shared/main-navigation/mat-main-nav/status-bar/status-bar.component.spec.ts, src/environments/constants.ts, src/environments/environment.interface.ts
* Concerns and recommendations are filtered on DBC
* DBC column in Recommendations visible for London users only
TISNEW-4629
=> TISNEW-4629  feat: Adding DBC codes to user information

src/app/core/auth/auth.service.ts, src/app/shared/main-navigation/mat-main-nav/status-bar/status-bar.component.ts
display email for key-cloak and full name in cognito
TISNEW-5421
=> fix: username in status-bar 

src/app/recommendations/recommendations.interfaces.ts, src/app/recommendations/services/recommendations.service.spec.ts, src/app/recommendations/state/recommendations.state.ts, src/app/records/record-list/record-list.component.spec.ts
=> fix: updated recommendation response property name TISNEW- 5434                                                            

src/app/admins/allocate-admin-autocomplete/allocate-admin-autocomplete.component.ts, src/app/records/record-list/record-list.component.html
=> TISNEW-5339 fix: Pre-populating the selected admin name

package.json, src/app/core/auth/auth.initializer.ts, src/app/core/auth/auth.interceptor.spec.ts, src/app/core/auth/auth.service.ts, src/environments/constants.ts, src/environments/environment.interface.ts
* Allow access for HEE Admin Revalidation only
TISNEW-5356
=> TISNEW-5356 feat: Read the dbcs and roles from the token

src/app/core/auth/auth.initializer.ts, src/app/core/auth/auth.service.ts
* If the user is assigned any of the london dbc
* Updated variable visibility
TISNEW-5356
=> fix: Add London dbcs to dbcs list

src/app/admins/admins.interfaces.ts, src/app/admins/services/admins.service.spec.ts, src/app/admins/state/admins.actions.ts, src/app/admins/state/admins.state.ts
=> fix: Updated admin dto according to endpoint

src/app/core/auth/auth.initializer.ts, src/app/details/details.module.ts, src/app/shared/services/error/error.service.ts
=> fix: Updated details.module with error interceptor

src/app/shared/services/error/error.service.ts
=> fix: Read error message from array or object

.aws/task-definition-prod.json, .github/workflows/deploy.yml, .github/workflows/prod.deploy.yml
add production deployment workflow and task definition for production
TISNEW-5487
=> chore: production workflow setup

.github/workflows/deploy.yml
=> chore: add docker pull before tagging stable and pushing to ECR

src/app/recommendation/create-recommendation/create-recommendation.component.ts, src/app/recommendation/services/recommendation-history.service.ts
=> fix: Handle error for deferral recommendation

src/app/recommendation/confirm-recommendation/confirm-recommendation.component.ts, src/app/recommendation/recommendation-history.interface.ts, src/app/recommendation/services/recommendation-history.service.spec.ts, src/app/recommendation/services/recommendation-history.service.ts, src/app/recommendation/state/recommendation-history.actions.ts, src/app/recommendation/state/recommendation-history.state.ts
=> feat: Passing dbc in gmc recommendation post TISNEW-5670

src/app/recommendation/create-recommendation/create-recommendation.component.html, src/app/recommendation/create-recommendation/create-recommendation.component.ts, src/app/recommendation/recommendation-history.interface.ts, src/app/recommendation/state/recommendation-history.state.ts
* Blocked calender dates with correct logic
* Added error messages for scenarios
TISNEW-5610
=> TISNEW-5610 fix: Deferral recommendation dates calculation

src/app/recommendation/state/recommendation-history.state.ts
* When a recommendation is under-review
TISNEW-5681
=> TISNEW-5681 fix: Hide create recommendation button

src/app/recommendations/constants.ts, src/app/recommendations/state/recommendations.state.spec.ts, src/app/recommendations/state/recommendations.state.ts
=> fix: update default sort column

src/app/app-routing.module.ts, src/app/concern/state/concern.state.spec.ts, src/app/connection/confirm-dialog/confirm-dialog.component.html, src/app/connection/confirm-dialog/confirm-dialog.component.spec.ts, src/app/connection/confirm-dialog/confirm-dialog.component.ts, src/app/connection/connection-routing.module.ts, src/app/connection/connection.component.html, src/app/connection/connection.component.scss, src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts, src/app/connection/connection.interfaces.ts, src/app/connection/connection.module.ts, src/app/connection/connection.resolver.ts, src/app/connection/constants.ts, src/app/connection/mock-data/conneciton-details-spec-data.ts, src/app/connection/services/connection.service.spec.ts, src/app/connection/services/connection.service.ts, src/app/connection/state/connection.actions.ts, src/app/connection/state/connection.state.spec.ts, src/app/connection/state/connection.state.ts, src/app/core/auth/auth.service.ts, src/scss/utilities/_layout.scss
=> feat: Added connection summary page

src/app/recommendation/create-recommendation/create-recommendation.component.ts, src/app/recommendations/constants.ts
=> fix: Updated deferral logic

src/app/connection/confirm-dialog/confirm-dialog.component.html, src/app/connection/connection.component.html, src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts, src/app/connection/connection.interfaces.ts, src/app/connection/connection.resolver.spec.ts, src/app/connection/connection.resolver.ts, src/app/connection/constants.ts, src/app/connection/mock-data/conneciton-details-spec-data.ts, src/app/connection/services/connection.service.spec.ts, src/app/connection/services/connection.service.ts, src/app/connection/state/connection.state.ts, src/app/shared/services/error/error.service.ts
=> feat: Updated connection

src/app/connection/connection.component.html, src/app/connection/connection.component.scss, src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts, src/app/connection/connection.module.ts, src/app/connection/services/connection.service.spec.ts, src/app/connection/state/connection.state.spec.ts, src/app/connection/update-connection/update-connection.component.html, src/app/connection/update-connection/update-connection.component.scss, src/app/connection/update-connection/update-connection.component.spec.ts, src/app/connection/update-connection/update-connection.component.ts, src/app/core/http-error/http-error.interceptor.ts
Moved the update connection form to a separate component so that it can be re-used in bulk connections.
=> feat: Created component for connection update

src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts, src/app/connection/connection.interfaces.ts, src/app/connection/services/connection.service.spec.ts, src/app/connection/services/connection.service.ts, src/app/records/records.component.spec.ts, src/app/records/records.component.ts
=> fix: Update connection update response handling

src/app/connection/connection.component.html, src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts
=> fix: get designated body code from the gmc not from tcs

src/app/details/details-side-nav/details-side-nav.component.html
=> fix: Show N/A when grade not available

src/app/recommendations/constants.ts, src/app/recommendations/recommendations.interfaces.ts, src/app/recommendations/services/recommendations.service.spec.ts, src/app/records/record-list/record-list.component.scss, src/app/records/record-list/record-list.component.spec.ts
=> feat: add GMC status in recommendation summary

src/app/admins/allocate-admin-actions/allocate-admin-actions.component.html, src/app/admins/allocate-admin-actions/allocate-admin-actions.component.scss, src/app/admins/allocate-admin-actions/allocate-admin-actions.component.spec.ts, src/app/admins/allocate-admin-actions/allocate-admin-actions.component.ts, src/app/admins/allocate-admin-autocomplete/allocate-admin-autocomplete.component.html, src/app/admins/allocate-admin-autocomplete/allocate-admin-autocomplete.component.ts, src/app/admins/services/admins.service.ts, src/app/details/comments/comments.component.spec.ts, src/app/recommendation/confirm-recommendation/confirm-recommendation.component.spec.ts, src/app/records/record-list/record-list.component.html, src/app/records/records.component.html
=> feat: Enhanced allocate admin view

src/app/connections/services/connections.service.ts, src/app/connections/state/connections.state.ts, src/app/records/record-list/record-list.component.html, src/app/records/record-list/record-list.component.ts, src/app/records/record-search/record-search.component.html, src/app/records/record-search/record-search.component.ts
* In connections summary view page
* Search and sort disabled in exceptions view
TISNEW-5795
=> feat: Filter connections by exceptions

src/app/connection/connection.component.html, src/app/connection/connection.component.ts, src/app/connection/connection.interfaces.ts, src/app/connection/mock-data/conneciton-details-spec-data.ts
=> fix: removed the dbc and connection status fields

src/app/connection/connection.component.html, src/app/connection/connection.component.ts, src/app/connections/constants.ts, src/app/core/auth/auth.service.ts, src/app/recommendation/recommendation-table/recommendation-table.component.html, src/app/recommendation/recommendation-table/recommendation-table.component.ts, src/app/records/record-search/record-search.component.html, src/app/records/record-search/record-search.component.ts, src/app/update-connections/update-connection/update-connection.component.ts, src/environments/constants.ts
- to allocate admin
- to update connections
- to create / edit recommendation
TISNEW-5817
=> feat: Applying super admin permission

src/app/connection/state/connection.state.ts, src/app/reference/services/reference.service.spec.ts, src/app/reference/services/reference.service.ts, src/app/update-connections/services/update-connections.service.spec.ts, src/app/update-connections/state/update-connections.actions.ts, src/app/update-connections/state/update-connections.state.spec.ts, src/app/update-connections/state/update-connections.state.ts, src/app/update-connections/update-connection/update-connection.component.spec.ts, src/app/update-connections/update-connection/update-connection.component.ts, src/environments/constants.ts, src/environments/environment.interface.ts
=> feat: Reading dbcs from reference endpoint

src/app/admins/allocate-admin-actions/allocate-admin-actions.component.spec.ts, src/app/concern/concern.component.html, src/app/concern/concern.component.spec.ts, src/app/concern/concern.component.ts, src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts, src/app/connections/connections.resolver.ts, src/app/core/auth/auth.interceptor.spec.ts, src/app/core/auth/auth.service.spec.ts, src/app/records/records.component.ts, src/app/shared/services/api/api.service.spec.ts, src/app/update-connections/constants.ts, src/app/update-connections/services/update-connections.service.spec.ts, src/app/update-connections/services/update-connections.service.ts, src/app/update-connections/update-connection/update-connection.component.spec.ts, src/app/update-connections/update-connections.interfaces.ts
- Improved test coverage
- Concern permissions
=> feat: Hide connecitons

sonar-project.properties, src/app/connections/connections.interfaces.ts, src/app/connections/mock-data/connecitons-spec-data.ts, src/app/connections/state/connections.state.spec.ts, src/app/connections/state/connections.state.ts, src/app/records/record-search/record-search.component.spec.ts, src/app/records/records.component.spec.ts, src/app/update-connections/services/update-connections.service.spec.ts
=> feat: Connections by hidden filter

src/app/connections/state/connections.state.spec.ts, src/app/records/records.component.spec.ts, src/app/update-connections/update-connection/update-connection.component.html, src/app/update-connections/update-connection/update-connection.component.spec.ts, src/app/update-connections/update-connection/update-connection.component.ts
=> feat: Unhide connections

src/app/shared/info-dialog/info-dialog.component.html, src/app/shared/info-dialog/info-dialog.component.spec.ts, src/app/shared/info-dialog/info-dialog.component.ts, src/app/shared/services/error/error.service.spec.ts, src/app/shared/services/error/error.service.ts, src/app/shared/services/snack-bar/snack-bar.service.ts, src/app/shared/shared.module.ts
=> feat: changed snackbar to matdialog model

src/app/connections/services/connections.service.spec.ts, src/app/connections/services/connections.service.ts
=> feat: pass dbcs in exception summary request url

src/app/connections/state/connections.state.ts, src/app/records/record-search/record-search.component.ts
enable search function for connection exception
and set the search label as  "Enter GMC no"
TIS21-264
=> feat: enable exception search

.github/workflows/deploy.yml
use `--all-tags` to explicitly push all docker tags
<NO-TICKET>
=> chore: attempt to fix pipeline deploy issue

src/app/connections/connections.interfaces.ts, src/app/connections/state/connections.state.spec.ts, src/app/connections/state/connections.state.ts
=> chore: update request url for Connected and Disconnected summary page

src/app/recommendation/create-recommendation/create-recommendation.component.ts
Change "our recommendation was saved..." to "Your recommendation was
saved..."
TIS21-1754
=> fix: Correct typo in popup message

src/app/records/record-list/record-list.component.html
=> fix: change wording of warning searching summary for no result found

src/app/recommendation/recommendation-table/recommendation-table.component.html
=> fix: recommendation comment handle html tags

src/app/recommendation/recommendation-history.interface.ts
=> fix: add recommendation status

src/app/details/details-side-nav/service/details-side-nav.service.ts, src/app/details/details-side-nav/state/details-side-nav.actions.ts, src/app/details/details-side-nav/state/details-side-nav.state.spec.ts, src/app/details/details-side-nav/state/details-side-nav.state.ts, src/app/details/notes-drawer/note-card/note-card.component.html, src/app/details/notes-drawer/note-card/note-card.component.spec.ts, src/app/details/notes-drawer/note-card/note-card.component.ts, src/environments/constants.ts, src/environments/environment.interface.ts
=> feat: edit note

src/environments/constants.ts
=> fix: rename reval role

src/app/concern/concern.component.html, src/app/concern/concern.component.spec.ts, src/app/concern/concern.component.ts, src/app/connection/connection.component.ts, src/app/core/auth/auth.service.spec.ts, src/app/core/auth/auth.service.ts, src/app/details/notes-drawer/notes-drawer.component.ts, src/app/recommendation/recommendation-table/recommendation-table.component.ts, src/app/records/record-search/record-search.component.html, src/app/records/record-search/record-search.component.ts, src/environments/constants.ts
=> fix: remove legacy role `RevalSuperAdmin`

src/app/recommendations/constants.ts
=> fix: sort doctors summary page by ascending order

.editorconfig, .github/workflows/deploy.yml, .github/workflows/pr-analysis.yml
=> chore: rename master to main

.gitignore, cypress.json, cypress/integration/app/recommendations/recommendations-filters/recommendations-filters.spec.ts, cypress/integration/app/recommendations/recommendations-list-paginator/recommendations-list-paginator.spec.ts, cypress/integration/app/recommendations/recommendations-list/recommendations-list.spec.ts, cypress/integration/app/recommendations/recommendations-search/recommendations-search.spec.ts, cypress/integration/app/recommendations/reset-recommendations-list/reset-recommendations-list.spec.ts, cypress/support/commands.js, cypress/support/index.d.ts
-- local setup for cypress e2e testing
-- fix some existing test, if they are easy, otherwise delete
TIS21-2529
=> test: test for cypress config and login

src/app/details/nav-bar/nav-bar.component.spec.ts, src/app/details/nav-bar/nav-bar.component.ts, src/app/shared/main-navigation/mat-main-nav/desktop-menu/desktop-menu.component.html, src/app/shared/main-navigation/mat-main-nav/desktop-menu/desktop-menu.component.ts, src/app/shared/main-navigation/mat-main-nav/menu-item.interface.ts, src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts, src/app/shared/main-navigation/mat-main-nav/mobile-menu/mobile-menu.component.html, src/app/shared/main-navigation/mat-main-nav/mobile-menu/mobile-menu.component.ts
=> feat: add Connections back to Stage menu

.github/workflows/deploy.yml, .github/workflows/prod.deploy.yml, README.md, cypress.json
Removing problematic reporting conf for now
There are compatibility issues with node 15+ so will look to use node 14
TIS21-2210: Run E2E Tests in pipeline
=> chore: add E2E step to deploy action

.github/workflows/deploy.yml, .github/workflows/pr-analysis.yml
=> chore(deps): Upgrade Node 12 -> 14

src/assets/environments/environment.json
I assume that this is a bit of copy pasta rather than intentional.
NO-CARD
=> fix: use environment specific bucket for concerns

src/app/recommendation/guards/not-submitted.guard.ts, src/app/recommendation/state/recommendation-history.state.ts
=> fix: edit recommendation button wrongly shown on `completed` recommendation

.github/workflows/deploy.yml
=> Remove duplicate env setting from deploy.yml

cypress.config.ts
Apologies for the multiple fixes, I'm aiming for most PRs this quarter!
=> Use correct cypress dashboard projectid

src/app/connections/connections.interfaces.ts, src/app/connections/connections.resolver.ts, src/app/connections/state/connections.state.spec.ts, src/app/connections/state/connections.state.ts
=> Fix spelling mistake

cypress/e2e/app/connections/connection-component/connection-component.cy.ts, cypress/e2e/app/connections/record-search/record-search-component.cy.ts, src/app/connection/connection.component.ts, src/app/connections/state/connections.state.ts, src/app/records/record-list/record-list.component.html, src/app/records/record-search/record-search.component.html
=> feat: remove connections actions from UI

README.md, cypress/e2e/app/connections/connection-component/connection-component.cy.ts, src/app/connection/connection.component.html, src/app/connection/connection.component.ts
TIS21-3736: Tidy up detail page view
=> feat: remove programme history from details view

src/app/connections/constants.ts
TICKET: https://hee-tis.atlassian.net/browse/TIS21-3733
=> feat: remove unwanted columns from table

.github/workflows/deploy.yml
- Update the deploy-to-prod job to use s3
- Remove ECS jobs - build, build-artifacts and dockerise
- Change AWS_S3_BUCKET and CLOUDFRONT_DISTRIBUTION_ID secrets to vars
TIS21-4043: CI/CD pipeline modification to deploy to S3 in parallel with existing pipeline
=> feat:update prod deployment to s3

.github/workflows/deploy.yml
=> fix:typo in env name as set in angular.json

src/app/connections/constants.ts
=> feat: show GMC dbc and TIS dbc for current connections and discrepancies

src/app/update-connections/update-connection/update-connection.component.html
Small fix for changing the button label from "Save" to "Submit" as users requested
TIS21-4752
=> feat: rename button label

src/app/connections/constants.ts
TIS21-4753: Reval Connections MVP: Sort By Programme Owner and Gmc Designated Body
TIS21-4754
=> feat: set GMC DB Prog owner columns to sortable

cypress/e2e/app/connections/summary-records-list.cy.ts
=> fix: cypress tests failing

src/app/connections/constants.ts, src/app/records/record-list/record-list.component.html
In the BE the programmeOwner field is labelled
tcsDesignatedBody.
TIS21-4753: Reval Connections MVP: Sort By Programme Owner and Gmc Designated Body
TIS21-4754
=> feat:rename prog owner column

.github/workflows/deploy.yml
Remove unused AWS credential secrets.
TIS21-4862
=> build: remove unused credentials

package.json, src/app/connection/connection.component.spec.ts, src/app/connection/connection.component.ts, src/app/connections/connections.component.spec.ts, src/app/connections/connections.component.ts
TIS21-5176 Pass admin to endpoint from FE when updating a connection - single or bulk
=> feat: save admin name when updating a connection

.github/workflows/deploy.yml, src/app/recommendations/recommendations.interfaces.ts, src/app/recommendations/state/recommendations.state.ts
Reverts Health-Education-England/tis-revalidation-v2#1240
=> Revert "Patch/restore recommendations list"

cypress/e2e/app/recommendations/filter-summary-records.cy.ts, package.json, src/app/core/auth/auth.service.spec.ts, src/environments/environment.common.ts, src/environments/environment.prod.ts
TIS21-5496: Update London DBCs for STAGE in FE
Fix PR 1241 to pass E2E
=> Chore/update London DBCs

package-lock.json
These files were reported as out of sync when running npm ci in pipeline. Run a clean npm install locally to update package-lock.json
NO TICKET
=> fix: sync of package.json and package-lock.json

package-lock.json, package.json
Needed to resync package and package-lock as npm ci command throws errors.
- Deleted node_modules folder
- Ran npm cache clean --force locally
- Ran npm i locally
- Tested running npm ci and no errors
- Both package and lock commited this time
NO TICKET
=> fix: error when running npm ci

package.json, src/app/records/record-list-paginator/record-list-paginator.component.html
Enable navigating the summary records list between first and last page of records
NO TICKET
=> feat: show first/last buttons on paginator

cypress/e2e/app/recommendations/filter-summary-records.cy.ts, cypress/support/commands.js, cypress/support/index.d.ts, package.json
Also, update abbreviations for DBCs
NO TICKET
=> fix: update login form fields

src/app/recommendation/submission-date/submission-date.component.spec.ts
=> chore: fix date in unit test

.github/workflows/deploy.yml, package-lock.json
Update pipeline to use clean install
TIS21-7621
=> chore: update package-lock file

cypress/e2e/app/records/filter-summary-records-po.ts, package.json, src/app/records/record-list-table-filters/record-list-table-filters.component.scss, src/app/records/record-list/state/record-list.state.ts, src/app/records/records.component.scss, src/app/records/services/records.service.ts, src/app/shared/form-controls/material-selection-list/material-selection-list.component.html
- Set filter panel visibility to true by default
- Reduce width of filter panel to allow more screen for table
- Add tooltip to long labels in filter panel that get truncated (there is only one)
- Set the summary list table columns to fit the window by default
- Update E2E
TIS21-7780
=> feat: set filter panel to show by default
