Health-Education-England/tis-revalidation-v2

package.json
src/app/core/trainee/constants.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.html
src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts
src/app/trainees/state/trainees.actions.ts
src/app/trainees/state/trainees.state.ts
src/app/trainees/trainee-list/trainee-list.component.html
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-list/trainee-list.component.ts
src/app/trainees/trainees.component.html
src/app/trainees/trainees.module.ts
src/scss/utilities/_index.scss
src/scss/utilities/_spacing-helpers.scss
src/scss/utilities/_utilities.scss

TISNEW-4176
- created new `reset-trainee-list` component to clear sorting params and filters
- added margins and padding helper scss file
- added default sorting col and direction to constants file and re-used in multiple places
- fixed issue with default sorting column not highlighting when trainee list is viewed without any query params

feat: clear all params and filters

---

src/app/app-routing.module.ts
src/app/dashboard/dashboard-routing.module.ts
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-list/trainee-list.component.ts

TISNEW-4193
pr to ensure that 
- `/trainees` and `/trainees?active=<columnName>&direction=<direction>&pageIndex=<page>` lists trainees
- `/trainees/:id` shows trainee details

chore: cater for trainee details route

---

src/app/app-routing.module.ts
src/app/core/trainee/constants.ts
src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.html
src/app/shared/main-navigation/mat-main-nav/mat-main-nav.component.ts
src/app/shared/page-not-found/page-not-found.component.html
src/app/shared/page-not-found/page-not-found.component.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts
src/app/trainees/state/trainees.state.spec.ts
src/app/trainees/state/trainees.state.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.spec.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-list/trainee-list.component.ts
src/app/trainees/trainees-routing.module.ts

TISNEW-4194
- ensured store changes route with ngZone [fixes console warning]
- updated unit tests 
- ensured route change action is dispatched after GetTrainees has resolved
- dispatched actions in trainee-list, paginator and reset-trainee-list components individually as opposed to multiple actions in an array. this improves the stores development mode console logging and makes it much nicer to debug;

chore: store should route with ngzone

---

src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts
src/app/trainees/state/trainees.actions.ts
src/app/trainees/state/trainees.state.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.spec.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-list/trainee-list.component.ts
src/app/trainees/trainee-search/trainee-search.component.html
src/app/trainees/trainee-search/trainee-search.component.spec.ts
src/app/trainees/trainee-search/trainee-search.component.ts
src/app/trainees/trainees.component.html
src/app/trainees/trainees.module.ts

TISNEW-4054
- added new search feature for trainees
- includes form validation
- includes unit tests
- ensured `searchQuery` is appended to api call
- ensured reset trainees list `Clear All` also resets search
- moved pagination query params check within `trainee-list` to ensure all query params are checked in same component upon ngOnInit life cycle

feat: trainee list search

---

src/app/core/trainee/trainee.service.spec.ts
src/app/core/trainee/trainee.service.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts
src/app/trainees/state/trainees.actions.ts
src/app/trainees/state/trainees.state.spec.ts
src/app/trainees/state/trainees.state.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.spec.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-list/trainee-list.component.ts
src/app/trainees/trainee-search/trainee-search.component.spec.ts
src/app/trainees/trainee-search/trainee-search.component.ts

moved `/trainees` route change out of store as recommended by Femi to a service in order to ensure state management focuses on state
- removed `UpdateTraineesRoute` action as no longer needed
- small code refactor including tests
- added tests for `TraineeService`

chore: move route change out from store

---

projects/hee-shared/src/lib/hotjar/hotjar.module.ts

window._hjSettings undefined error in bootstrapping hotjar fix. object was not created
TISNEW-3849

fix: hotjar console error. added settings to window before script load

---

src/app/core/trainee/trainee.interfaces.ts
src/app/core/trainee/trainee.service.spec.ts
src/app/core/trainee/trainee.service.ts
src/app/trainees/state/trainees.state.spec.ts
src/app/trainees/state/trainees.state.ts
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.html
src/app/trainees/trainee-list-paginator/trainee-list-paginator.component.ts
src/app/trainees/trainee-list/trainee-list.component.html
src/app/trainees/trainee-list/trainee-list.component.ts
src/app/trainees/trainee-search/trainee-search.component.spec.ts
src/app/trainees/trainee-search/trainee-search.component.ts
src/environments/environment.ts

TISNEW-4208
- catered for `No results found` in the ui
- updated `IGetTraineesResponse` interface to align with BE
- ensured pagination is binding to `totalResults`
- updated and added unit tests
- cleaned up state and leveraged `patchState` instead of `setState`

feat: no results found for trainees search

---

src/app/core/trainee/trainee.service.spec.ts
src/app/core/trainee/trainee.service.ts
src/app/trainee/revalidation-history/revalidation-history.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-search/trainee-search.component.html
src/app/trainees/trainee-search/trainee-search.component.spec.ts
src/app/trainees/trainee-search/trainee-search.component.ts

In the scenario where there are validation errors on the trainee search form and the `Clear all` button is pressed then reset the search form.
- also fix material table related warnings in spec files

feat: reset form on clear all

---

projects/hee-shared/src/lib/utilities.functions.ts
src/polyfills.ts

there was an issue which meant build shared modules before referencing imports.
Directly implemented self executing function in polyfills.ts to resolve

fix: broken pipeline.

---

src/app/trainees/trainee-list/trainee-list.component.html

angular's `innerHtml` was causing material's `mat-header-cell` html to not render and therefore the sorting icon and hover state was not visible

fix: missing sorting icon

---

src/app/concerns/concern-list/concern-list.component.spec.ts
src/app/concerns/state/concerns.actions.ts
src/app/core/trainee/trainee.service.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.spec.ts
src/app/trainees/reset-trainee-list/reset-trainee-list.component.ts
src/app/trainees/state/trainees.actions.ts
src/app/trainees/state/trainees.state.spec.ts
src/app/trainees/state/trainees.state.ts
src/app/trainees/trainee-filters/trainee-filters.component.spec.ts
src/app/trainees/trainee-filters/trainee-filters.component.ts
src/app/trainees/trainee-list/trainee-list.component.html
src/app/trainees/trainee-list/trainee-list.component.spec.ts
src/app/trainees/trainee-list/trainee-list.component.ts

TISNEW-4573
make actions, state generic so that common code can be leveraged and consumed by both trainees list and concerns list. so basically `AllDoctorsFilter` and `UnderNoticeFilter` have been replaced by a generic filter as `Filter` with a payload

refactor: make actions, state generic

---

package-lock.json
src/app/trainee/revalidation-table/revalidation-table.component.html
src/app/trainee/revalidation-table/revalidation-table.component.spec.ts

console error and unit test warnings
most of the code changes are auto formatting done by prettier. actual changes are; 
- `revalidationHistory.length > 0` to `revalidationHistory?.length > 0` to fix console error
- and importing `MaterialModule`, `NoopAnimationsModule` in the spec file to get rid of the material table warnings

fix: console error and unit test warnings

---

.github/workflows/deploy.yml

Installing dependencies takes a considerable portion of the workflow run
time, this can be reduced by enabling caching of the node_modules.
NO-TICKET

chore: Add dependency caching to workflow

---

README.md
angular.json
custom-webpack.config.js
package-lock.json
package.json
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/shared/admins/services/admins.service.spec.ts
src/app/shared/admins/services/admins.service.ts
src/app/shared/admins/state/admins.actions.ts
src/app/shared/admins/state/admins.state.spec.ts
src/app/shared/admins/state/admins.state.ts
src/environments/constants.ts
src/environments/environment.interface.ts

TISNEW-4829
feat: get admin users list
- fetch admins list via aws cognito sdk api and store on `admins` state slice
- invoke `Get` admins action from app component as the admins list is to be used across all summary & details pages
- extend default angular webpack config so that environment variables can be consumed for AWS `secretAccessKey` & `AWS_ACCESS_KEY_ID`
- updated `README.md`

get admin users list

---

src/app/concerns/concerns.resolver.ts
src/app/concerns/state/concerns.actions.ts
src/app/concerns/state/concerns.state.ts
src/app/connections/connections.resolver.ts
src/app/connections/state/connections.actions.ts
src/app/connections/state/connections.state.ts
src/app/recommendations/recommendations-filters/recommendations-filters.component.spec.ts
src/app/recommendations/recommendations-filters/recommendations-filters.component.ts
src/app/recommendations/recommendations-list-paginator/recommendations-list-paginator.component.spec.ts
src/app/recommendations/recommendations-list-paginator/recommendations-list-paginator.component.ts
src/app/recommendations/recommendations-list/recommendations-list.component.scss
src/app/recommendations/recommendations.resolver.ts
src/app/recommendations/services/recommendations.service.spec.ts
src/app/recommendations/state/recommendations.actions.ts
src/app/recommendations/state/recommendations.state.spec.ts
src/app/recommendations/state/recommendations.state.ts
src/app/shared/material/material.module.ts
src/app/shared/records/allocate-admin-actions/allocate-admin-actions.component.html
src/app/shared/records/allocate-admin-autocomplete/allocate-admin-autocomplete.component.html
src/app/shared/records/allocate-admin-autocomplete/allocate-admin-autocomplete.component.spec.ts
src/app/shared/records/allocate-admin-autocomplete/allocate-admin-autocomplete.component.ts
src/app/shared/records/record-list/record-list.component.html
src/app/shared/records/record-list/record-list.component.spec.ts
src/app/shared/records/record-search/record-search.component.html
src/app/shared/records/record-search/record-search.component.spec.ts
src/app/shared/records/record-search/record-search.component.ts
src/app/shared/records/records.module.ts
src/app/shared/records/reset-record-list/reset-record-list.component.spec.ts
src/app/shared/records/state/records.actions.ts
src/app/shared/records/state/records.state.ts

TISNEW-4831
- put back concerns, connections and recommendations actions as they are needed for NGXS to distinguish between which state store to work from. updated specs, state, components, resolvers accordingly
- created new `AllocateAdminAutocomplete` component in order to display and filter admins list on the ui once in allocate admin mode
- ensured search component validation is triggered on submit instead of blur as requested

feat: allocate admin

---

src/app/shared/records/constants.ts
src/app/shared/records/record-list/record-list.component.html
src/app/shared/records/record-list/record-list.component.scss
src/app/shared/records/record-list/record-list.component.spec.ts

NO-TICKET
conditionally displaying checkbox cell
- cleanup and simplify markup to ensure an extra table cell is not created when allocate admin is enabled. when allocate admin is disabled it was causing an empty cell to render

fix: conditionally displaying checkbox cell

---

package-lock.json
package.json
src/app/concern/concern.interfaces.ts
src/app/concern/constants.ts
src/app/concern/file-uploader/file-uploader.component.html
src/app/concern/file-uploader/file-uploader.component.spec.ts
src/app/concern/file-uploader/file-uploader.component.ts
src/app/concern/services/upload/upload.service.spec.ts
src/app/concern/services/upload/upload.service.ts
src/app/concern/state/concern.actions.ts
src/app/concern/state/concern.state.ts
src/app/concern/uploaded-files-list/uploaded-files-list.component.html
src/app/concern/uploaded-files-list/uploaded-files-list.component.spec.ts
src/app/concern/uploaded-files-list/uploaded-files-list.component.ts
src/environments/constants.ts
src/environments/environment.interface.ts
src/environments/environment.mocky.ts

TISNEW-5022
feat: consume download api
- added `file-saver` npm package in order to save file
- added `DownloadFile` and `DownloadFileSuccess` actions and relevant listener methods
- created `IListFile` interface and typed list files endpoint response
- extracted common bucket name `FILE_BUCKET_NAME` to a variable 
- added unit tests

feat: consume download api

---

src/app/concern/services/upload/upload.service.ts

TISNEW-5023
fix: response type as delete api returns a string

fix: response type

---

angular.json
package-lock.json
package.json
src/app/admins/admins.interfaces.ts
src/app/admins/admins.module.ts
src/app/admins/allocate-admin-autocomplete/allocate-admin-autocomplete.component.html
src/app/admins/allocate-admin-autocomplete/allocate-admin-autocomplete.component.ts
src/app/admins/services/admins.service.spec.ts
src/app/admins/services/admins.service.ts
src/app/admins/state/admins.actions.ts
src/app/admins/state/admins.state.spec.ts
src/app/admins/state/admins.state.ts
src/environments/constants.ts
src/environments/environment.interface.ts
src/environments/environment.mocky.ts

TISNEW-4977
refactor: consume admin endpoints
- strip out aws-sdk, aws secret/s as not needed anymore

refactor: consume admin endpoints

---

README.md
cypress.json
cypress/integration/app/app.spec.ts
cypress/integration/app/recommendations/recommendations-filters/recommendations-filters.spec.ts
cypress/integration/app/recommendations/recommendations-list-paginator/recommendations-list-paginator.spec.ts
cypress/integration/app/recommendations/recommendations-list/recommendations-list.spec.ts
cypress/integration/app/recommendations/recommendations-search/recommendations-search.spec.ts
cypress/integration/app/recommendations/reset-recommendations-list/reset-recommendations-list.spec.ts
cypress/support/commands.js

NO-TICKET
fix: e2e tests
The pr addresses the issue of login & as well as fixes the broken tests.
- The externally hosted aws cognito login screen is filled in and submitted
- the baseUrl has been set to staging as cypress doesn't allow tests to run on different domains. The only other option I could think of was to progmatically login via `cy.request()` but this would expose AWS secrets which is not a good idea

fix: e2e tests

---

src/app/concern/concern.interfaces.ts
src/app/concern/constants.ts
src/app/concern/create-concern-forms/concern-detail/concern-detail.component.html
src/app/concern/create-concern-forms/concern-detail/concern-detail.component.spec.ts
src/app/concern/create-concern-forms/concern-detail/concern-detail.component.ts
src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.html
src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.spec.ts
src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.ts
src/app/concern/create-concern-forms/upload-documents/upload-documents.component.spec.ts
src/app/concern/create-concern-forms/upload-documents/upload-documents.component.ts
src/app/concern/resolvers/create-edit-concern.resolver.spec.ts
src/app/concern/resolvers/create-edit-concern.resolver.ts
src/app/concern/services/concern/concern.service.ts
src/app/concern/state/concern.actions.ts
src/app/concern/state/concern.state.ts
src/app/concern/uploaded-files-list/uploaded-files-list.component.ts
src/app/recommendation/mock-data/recommendation-spec-data.ts
src/environments/constants.ts
src/environments/environment.interface.ts
src/environments/environment.mocky.ts

TISNEW-5042
feat: add concern
- consumed add concern api in the FE & only create concern if form steps are valid
- consumed newly exposed list of types and sources to populate dropdowns in the FE & removed hard coded lists
- fixed duplicate list files api call by triggering once `OnInit` instead of listening to create concern state updates
- ensured add concern state is persisted when navigating between steps
- updated FE mocks (mocky & spec data)
- simplified forms and updated unit tests

feat: add concern

---

src/app/concern/create-concern-forms/concern-detail/concern-detail.component.ts
src/app/concern/services/concern/concern.service.ts
src/app/concern/services/upload/upload.service.ts
src/app/shared/services/api/api.service.spec.ts
src/app/shared/services/api/api.service.ts
src/app/shared/shared.module.ts

TISNEW-5042
refactor: create generic enum key grabber in order to send BE enum keys when invoking api's
- also set responseType to text for add concern api

refactor: create generic enum key grabber

---

src/app/recommendations/recommendations.resolver.ts
src/app/recommendations/state/recommendations.state.spec.ts
src/app/recommendations/state/recommendations.state.ts
src/app/records/record-list-filters/record-list-filters.component.html
src/app/records/record-list-filters/record-list-filters.component.ts
src/app/records/records.interfaces.ts
src/app/records/services/records.service.ts
src/app/records/state/records.state.ts

NO-TICKET
refactor | make filters generic | step 2. Leftover work to complete making filters generic so that the same code can be used across recommendations, concerns and connections

refactor | make filters generic | step 2

---

src/app/admins/state/admins.state.ts
src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.spec.ts
src/app/concern/create-concern-forms/trainee-detail/trainee-detail.component.ts
src/app/concern/create-concern-forms/upload-documents/upload-documents.component.ts
src/app/records/record-list/record-list.component.spec.ts
src/app/records/record-list/record-list.component.ts
src/environments/environment.mocky.ts

NO-TICKET
fix: clear any pending admin changes on summary and create concern screens when components are destroyed  
- update mock endpoints
- remove unused imports

fix: clear pending admin changes

---

.aws/task-definition.json

The memory and cpu are set unnecesarily high for the stage tasks, reduce
them down to the smallest allowed values.
NO-TICKET

chore: Set stage task to minimum resource amounts

---

src/app/details/comments/comments.component.ts

Inelegant fix for a UI error. Root cause of the issue is lack of handling of instances where featureComments is null when passed to the comments component. In local builds this does not present an issue but on staging & prod this causes the form rendering to crash.

Âfix: edit recommendation render error

---

src/scss/nhsuk/_globals.scss

The NHS and fallback font strings are concatenated which was resulting in a font name Frutiger W01Arial.  Fonts now wrapped in quotes to correct this.

fix:add quotes to correct font concatenation

---

src/app/core/auth/auth.service.ts
src/app/recommendation/create-recommendation/create-recommendation.component.html
src/app/recommendation/create-recommendation/create-recommendation.component.ts
src/environments/constants.ts

There are 3 roles in revalidation arena. They are "RevalApprover", "RevalAdmin" and "RevalObserver". Reval approver can read, write and make recommendation, Reval admin can read and write but should not be allowed to make recommendation. This fix will take care of that.
Reval Observer has only read permission, which has already been handled in the app. 
For more info, please refer to this page
https://hee-tis.atlassian.net/wiki/spaces/NTCS/pages/1671495738/Revalidation+-+Access+Permissions
TIS21-2272

fix: remove make recommendation from reval admin role

---

src/app/details/nav-bar/nav-bar.component.spec.ts
src/app/details/nav-bar/nav-bar.component.ts
src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts

TIS21-2021
- hiding from main menu by changing the "type" to 9, so that desktop-menu.component.html file's logic does not match
- hiding from the navigation bar by commenting the code, we will need this code later

chore: hide concern and connection from main and navigation menu

---

package-lock.json
package.json

There is a critical security vulnerability in a transitive dependency.
**N.B.** I've had a quick look through the aws-aplify/auth changelog but haven't managed to test this locally so there is a greater chance of problems with the app, which we have some E2E tests for.

chore(deps): upgrade aws-aplify 3.022 -> 3.4.3

---

.github/workflows/deploy.yml

The E2E in pipeline failed with the following error.
`You are attempting to use Cypress with an older config file: cypress.json
When you upgraded to Cypress v10.0 the config file was updated and moved to a new location: cypress.config.ts`
cypress.json no has already been updated so maybe a simple fix following upgrade of Cypress from 7 -> 10, as suggested here:-  
https://github.com/cypress-io/github-action/issues/568
NO TICKET

Update the Cypress github action following Cypress upgrade

---

src/app/records/record-search/record-search.component.html
src/app/records/record-search/record-search.component.ts

Update search box label to include 'programme'. The original code was trying to set the field name conditionally depending upon the current view, although this wasn't working correctly. This has been removed and the label set statically since the name search works from the exceptions queue view and there appears to be no reason to block this or programme name search.
https://hee-tis.atlassian.net/browse/TIS21-3058

feat:set label removing the broken conditional and widen field

---

src/app/app.component.ts

The HTML page title displays `Revalidation` for all page routes. It would be better to give if this provided more detail for improved UX and analytics data capture. The addition of title custom data properties has already been included in the routes eg  `data: { title: "Connections list" }`. However, the code to actually update the page title was absent.
NO TICKET

Add page titles to DOM

---

src/app/records/record-list-table-filters/record-list-table-filters.component.spec.ts
src/app/records/services/records.service.ts

A bug was spotted whereby when a user navigates from recommendation summary table to the trainee details screen and then clicks the back button to return to the summary, the filter panel is blank since the form data is empty. By swapping the Subject to a BehaviorSubject, the latest value for this form data property is retrieved on subscription.

fix: blank filter form displayed after loading doctor's detail screen  

---

src/assets/environments/environment.json

The backend core service reuses the sentry environment name for the environment endpoint, the result of that endpoint is used by the frontend to select a set of variables per environment. The sentry environment env var was changed from `stage` to `preprod` in the backend, change the lookup value in the front end to match this change.
The `environment.name` value was left as `stage` as I'm not sure the full impact and this is a quick fix to get the stage app working again.
TIS21-3497
TIS32-3849

fix: update environment name from stage to preprod

---

cypress/e2e/app/recommendations/filter-summary-records.cy.ts

Believe the test is failing due to the value displayed being updated before being read. To fix, the test waits for the doctors table to display before and after clicking the All Doctors tab.

test:add table check after nav and prior to test

---

src/app/records/record-list-table-filters/record-list-table-filters.component.spec.ts
src/app/records/record-list-table-filters/record-list-table-filters.component.ts

An issue was found when a user had paginated through the doctors list and then applied a filter resulting in a blank page even though matching results were found. Now, when the filter is applied, pagination is reset to zero first.

feat:reset pagination on filtering

---

src/assets/environments/environment.json
src/main.ts

Need to set sign/out domain for alpha. Conditional test for alpha domain temporary so detection via `window.location` should suffice.

feat:add alpha env variables for callback

---

.github/workflows/deploy.yml

build, backup-artifacts and dockerise jobs remain fir now as required for deployment to prod ECS.
Add Slack messages to pre prod s3 deploy
TIS21-4043: CI/CD pipeline modification to deploy to S3 in parallel with existing pipeline

feat: remove ECS pre-prod deploy job

---

src/app/core/auth/auth.service.spec.ts
src/environments/constants.ts
src/environments/environment.preprod.ts
src/environments/environment.prod.ts
src/environments/environment.ts

This change impacts PROD DBCs only following
the announcement that GMC do not intend to update
the code on their test environment.
When the new codes have been published, the only change required is to update the values in `environment.prod.ts`
TIS21-4239: Add new DBCs to reval front end (Auth service, E2E tests)

feat: update gmc dbc values

---

.github/workflows/deploy-alpha.yml
angular.json
src/app/shared/main-navigation/mat-main-nav/menu-items.const.ts
src/environments/environment.alpha.ts
src/environments/environment.common.ts
src/environments/environment.interface.ts
src/environments/environment.preprod.ts
src/environments/environment.prod.ts
src/environments/environment.ts

The main reason for creating the separate alpha environment is to enable the `redirectSignIn` and `redirectSignOut` properties to point to the alpha domain instead of stage.
Relates to this closed PR
https://github.com/Health-Education-England/tis-revalidation-v2/pull/1081
NO TICKET

feat:add configs for alpha environment

---

src/environments/environment.alpha.ts
src/environments/environment.preprod.ts
src/environments/environment.prod.ts

The awsConfig settings are in a nested object in the env variables. The spread operator was simply overwriting rather than appending to these properties. Fix to append the awsConfig separately.
Relates to this closed PR
https://github.com/Health-Education-England/tis-revalidation-v2/pull/1082
NO TICKET

fix:awsConfig env variables being overwritten

---

src/app/recommendation/confirm-recommendation/confirm-recommendation.component.html
src/app/recommendation/confirm-recommendation/confirm-recommendation.component.spec.ts
src/app/recommendation/confirm-recommendation/confirm-recommendation.component.ts

Repeated clicking of button to submit recommendation triggers multiple requests to the GMC, which they have flagged. The button is now disabled after the first click preventing subsequent clicking until after the submission is complete.
TIS21-4371: Prevent repeated clicking of Submit to GMC button during submission

feat: disable recommendation submit on click

---

.github/workflows/deploy.yml

The Slack notifications sent to reval-pipeline channel on deployment to pre-prod and prod are redundant
since they are already sent to the notifications-deployments channel.
NO TICKET

chore: remove Slack notification in GHA

---

cypress/e2e/app/recommendations/filter-summary-records.cy.ts

TIS21-4655: Display the DBC as an abbreviation instead of code in summary records table

test:update dbcs to use abbreviations in E2E test

---

package-lock.json
src/app/connections/connections.resolver.ts
src/app/recommendations/recommendations.resolver.ts

Changing tabs in recommendations and connections is opening the filter panel. This is due to core query params getting added when switching tabs and so params do then exist. Main change is checking if table filter params exist. The rest is refactoring to make it cleaner and more generic.
NO TICKET

fix: setting filter state in resolver

---

cypress/e2e/app/recommendations/save-submit-recommendation.cy.ts

Fix conditional and add return false to break the loop.
TIS21-4548: Correctly handle situations where a doctor exists in GMC but not in TIS on the connection and recommendation details pages
TIS21-4733

test:fix E2E test

---

.github/workflows/deploy-alpha.yml

Remove the unused ecr user tokens and replace it with a role reference to the github-actions-deployer-role accessible using OIDC.
TIS21-4862

build: use OIDC for AWS credentials

---

package.json
src/app/connection/connection.resolver.ts
src/app/recommendation/recommendation.resolver.ts

Due to the intermittent delay in fetching data from Trainee endpoint on Prod, the previous fix wasn't sufficient. CombineLatest waits for items to be emitted from both observables before returning and resolving to the details page.
The browser won't navigate to the details page until data is returned so when there is any significant delay, there is no indication in the UI that the details page is loading. Either the performance issues will need addressing or some form of loading spinner could be added.
TIS21-4868 - Prevent details page from initially displaying previous loaded doctor's details in the trainee profile panel

fix: return both data fetches once complete

---

.github/workflows/README.md

Document the required AWS permissions for running the deployment workflow.
Specifically, those required to:
- Back up build artifacts to S3
- Deploy static website content to S3
- Invalidate the Cloudfront cache
TIS21-4996
TIS21-4949

docs: required permissions for deploy workflow

---

cypress/e2e/app/connections/update-connection.cy.ts
package.json

The previous doctor used for testing connections was throwing an error possibly caused by using a fake doctor. This has been changed to use a different account.
NO TICKET

test: change doctor used for connections E2E

---

cypress/e2e/app/connections/summary-records-list.cy.ts

TIS21-5250: Rename Exception Logs to "Failed GMC Updates" in FE

test: update tab label

---

.github/workflows/deploy.yml

Using the clear-runs workflow from .github repo to reject outdated runs. Environment prod is passed in to trigger clear-runs after prod deployment approval.
NO TICKET

chore: clear outdated runs in deploy workflow
